# Generated by Django 5.2.17 on 2026-09-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_station_coordinate_source'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fuelpriceobservation',
            new_name='routes_fuel_station_3feb70_idx',
            old_name='routes_fuel_station_0d31fd_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelpriceobservation',
            new_name='routes_fuel_station_5b35a0_idx',
            old_name='routes_fuel_station_7f6b61_idx',
        ),
    ]
